# docker build -f .devcontainer/Dockerfile.dev -t mam10eks/trec-tot-anserini-baseline:dev-0.0.1 .
FROM ubuntu:jammy

RUN apt-get update && apt-get install -y openjdk-21-jdk python3 python3-pip git wget

ADD requirements.txt /

# Install dependencies and ensure pyterrier resources are cached
RUN pip3 install -r /requirements.txt \
	&& rm /requirements.txt \
	&& mkdir /app \
	&& wget https://repo1.maven.org/maven2/io/anserini/anserini/1.0.0/anserini-1.0.0-fatjar.jar -O /app/anserini.jar
