# docker build -f .devcontainer/Dockerfile.dev -t mam10eks/trec-tot-lightning-ir-baseline:dev-0.0.1 .
FROM nvcr.io/nvidia/cuda:12.8.0-cudnn-devel-ubuntu24.04

RUN apt-get update && apt-get install -y python3-pip git

ADD requirements.txt /


# Install dependencies
RUN pip3 install -r /requirements.txt --break-system-packages \
	&& rm /requirements.txt
